In [1]:
%load_ext autoreload
%aimport -keras
%autoreload 2

In [2]:
import random
import os
import matplotlib.pyplot as plt
import argparse
import keras
from utils import *
from models.lstm_classifier import LSTMClassifier
from models.gru_classifier import GRUClassifier

Using TensorFlow backend.


In [3]:
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

## Train the model

In [4]:
train = load_data('data/utterances.train')
val = load_data('data/utterances.valid')

In [5]:
train = pd.concat([train, val]).sample(frac=1) # Merge train & val then shuffle
val_split = len(val) / len(train)
val_split

0.09237789951132092

In [6]:
test = load_data('data/utterances.test', train=False)

In [7]:
classes = train['dialog_act'].unique()
num_classes = len(classes)
max_len = train['utterance_t'].apply(len).max()

In [8]:
(X_train, y_train), (vocab, word_to_idx, idx_to_word) = process_data(train, max_len)

In [9]:
test_vocab = [word for row in test['utterance_t'] for word in row if word not in vocab]
for word in test_vocab:
    idx = len(word_to_idx)
    word_to_idx[word] = idx
    idx_to_word[idx] = word
    vocab.add(word)

In [10]:
weights = {}
with open('/projekte/slu/share/emb/glove.twitter.27B.50d.txt', 'r', encoding='utf-8') as f:
    for line in f.readlines():
        line = line.split()
        word = line[0]
        if word in vocab:
            weights[word] = np.array(line[1:], dtype='float32')

In [11]:
# embds_path = '/projekte/slu/share/GoogleNews-vectors-negative300.bin' 
# weights = load_bin_vec(embds_path, word_to_idx)

In [12]:
num_dims = weights[random.choice(list(weights.keys()))].shape[0]
add_unknown_words(weights, word_to_idx, k=num_dims, min_df=0)
W, word_idx = get_W(weights, k=num_dims)

In [ ]:
#model = GRUClassifier(num_classes, max_len, W)
model = LSTMClassifier(num_classes, max_len, W)

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam', metrics=['accuracy'])
print(model.summary())

## Test the model

In [ ]:
%%time
history = model.fit(X_train, y_train, validation_split=val_split * 2,
                    epochs=3, batch_size=64)

In [19]:
model = keras.models.load_model('gru_100_epochs.h5')

In [20]:
X_test = sequence.pad_sequences(test['utterance_t'].apply(process_seq, args=[word_idx]),
                                maxlen=max_len)

In [21]:
pred = model.predict_classes(X_test)
pred

array([4, 0, 0, ..., 0, 0, 2])

In [22]:
counts = np.unique(pred, return_counts=True)
counts

(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([8768,  296, 8321,    3,  375,  357,    4,   73,  539,   61,    2,
          18,   49,   32,   58,   33,   19,    3,   73,  122,    7,    7,
           7,    8,    6,  555,    3,   59,  141,    1]))

In [23]:
counts = np.unique(pred, return_counts=True)
pred_out = pd.Series(dict([(classes[i], c / len(pred))
                           for i,c in list(zip(counts[0], counts[1]))]), name='dialog_act')
train_out = (train.groupby('dialog_act').size() / len(train))
merged = pd.DataFrame(data=dict(pred_out=pred_out, train_out=train_out)).dropna()
merged['% dif'] = (merged['pred_out'] - merged['train_out']) * 10
merged['rank dif'] = ((merged['pred_out'].rank() - merged['train_out']
                       .rank())
                       .abs()
                       .astype(int))

In [24]:
merged.sort_values(by='train_out', ascending=False)

pred_out  train_out     % dif  rank dif
s     0.43840   0.497256 -0.588564         0
b     0.41605   0.195615  2.204352         0
aa    0.01785   0.074276 -0.564265         3
%     0.01875   0.042974 -0.242242         1
%--   0.01480   0.038933 -0.241327         2
ba    0.00365   0.024342 -0.206916         4
qy    0.00010   0.022028 -0.219275        22
x     0.02695   0.016836  0.101141         4
bk    0.00015   0.013224 -0.130739        18
qw    0.00305   0.010319 -0.072686         2
ar    0.00165   0.009917 -0.082668         5
h     0.00245   0.008453 -0.060026         3
d     0.00365   0.006448 -0.027980         2
bh    0.00015   0.004887 -0.047368        13
bs    0.00160   0.004480 -0.028803         2
co    0.00020   0.004134 -0.039339         9
bc    0.00030   0.004092 -0.037923         7
2     0.00040   0.004060 -0.036600         2
qo    0.00035   0.003118 -0.027678         3
qh    0.00090   0.002859 -0.019591         1
br    0.00610   0.001492  0.046081        12
g     0.00290   0.001316  0.015836         8
qrr   0.00035   0.001095 -0.007447         1
cc    0.00705   0.001012  0.060385        16
t3    0.00295   0.000933  0.020170        12
bd    0.00095   0.000822  0.001278         8
t1    0.00035   0.000813 -0.004629         5
aap   0.02775   0.000725  0.270248        25
fa    0.00005   0.000642 -0.005920         1
ft    0.00015   0.000494 -0.003442         3

In [25]:
for p, c in zip(pred[:20], test['utterance_t'].iloc[:20]):
    print(classes[p], c)

% ['<START>', 'But', 'once', 'we', 'once', 'we', "'ve", 'done', 'the', 'intellectual', 'part', 'of', 'these', ',', 'uh', ',', 'we', 'can', 'just', 'knock', 'them', 'out', ',', 'right', '?', '<END>']
s ['<START>', 'And', 'the', ',', 'uh', ',', 'Aurora', 'HTK', ',', 'it', 'was', 'like', 'twenty', '.', '<END>']
s ['<START>', 'Mmm', '.', '<END>']
b ['<START>', 'So', 'y', 'the', 'example', 'is', ',', '"', 'That', 'would', 'be', 'hard', '"', '<END>']
%-- ['<START>', 'Well', ',', 'or', 'if', 'you', "'re", 'a', 'C', 'programmer', '.', '<END>']
b ['<START>', 'if', 'they', "'re", 'right', 'next', 'to', 'one', 'another', '?', '<END>']
s ['<START>', 'That', "'s", 'interesting', '.', '<END>']
b ['<START>', 'I', "'d", 'expect', 'it', 'to', 'be', 'a', 'minor', 'effect', ',', '<END>']
b ['<START>', 'Mmm', '?', '<END>']
s ['<START>', 'Mm', '-', 'hmm', '.', '<END>']
s ['<START>', 'Alright', '.', '<END>']
b ['<START>', 'It', 'was', 'bo', 'it', 'both', 'times', 'the', 'same', 'person', '.', '<END>']
b ['<

In [26]:
test['prediction'] = [classes[p] for p in pred]
test.head()

utterance_t-3  \
utterance_ID                                                      
Bmr003_2578                                       I have to do    
Bro027_44                                                 Um ,    
Bro015_42     Oh so take a real VAD but apply it to to to th...   
Btr002_235    boy , it 's hard to ig uh , ignoi that ignore ...   
Bmr016_1398           In Monty Python you say " argh " a lot .    

                                                  utterance_t-2  \
utterance_ID                                                      
Bmr003_2578                    [<START>, that, 's, true, <END>]   
Bro027_44     [<START>, but, one, of, the, differences, that...   
Bro015_42                               [<START>, Uh, g, <END>]   
Btr002_235                      [<START>, Uh, -, huh, ., <END>]   
Bmr016_1398                       [<START>, Oh, yeah, ?, <END>]   

                                                  utterance_t-1  \
utterance_ID                                                      
Bmr003_2578   [<START>, but, we, haven't, spent, that, ,, ri...   
Bro027_44                              [<START>, Yep, ., <END>]   
Bro015_42     [<START>, Yeah, ,, to, the, clean, and, take, ...   
Btr002_235                              [<START>, Um, ,, <END>]   
Bmr016_1398                             [<START>, So, ., <END>]   

                                                    utterance_t prediction  
utterance_ID                                                                
Bmr003_2578   [<START>, But, once, we, once, we, 've, done, ...          %  
Bro027_44     [<START>, And, the, ,, uh, ,, Aurora, HTK, ,, ...          s  
Bro015_42                              [<START>, Mmm, ., <END>]          s  
Btr002_235    [<START>, So, y, the, example, is, ,, ", That,...          b  
Bmr016_1398   [<START>, Well, ,, or, if, you, 're, a, C, pro...        %--

In [ ]:
with open('3372489_sorensen_topic1_result.txt', 'w') as fout:
    for idx, p in test['prediction'].iteritems():
        fout.write(f'{idx} {p}\n')